#!/usr/bin/env bash
# Parts of this is ai generated (interactive part)
# Usage: ./setup.sh [preset | <hf-user>/<repo>[:<quant>]]
#   Optional env: LLAMA_API_KEY, CTX_SIZE, PARALLEL, TEMPERATURE, TOP_P, N_CPU_MOE, SPLIT_MODE, PORT, HF_TOKEN
set -Eeuo pipefail
cd "$(dirname "$0")"

die() { echo "error: $*" >&2; exit 1; }

# GPU type | VRAM per GPU (GB)
GPUS=("A10G|24" "L4|24" "L40S|48" "A6000|48" "A100-40GB|40" "A100-80GB|80" "H100|80" "H200|141")

# name | MODEL | download GB | min total VRAM GB | CTX_SIZE | TEMPERATURE | TOP_P
PRESETS=(
    "nemotron-9b|bartowski/nvidia_NVIDIA-Nemotron-Nano-9B-v2-GGUF:Q8_0|9.5|16|131072|0.6|0.95"
    "nemotron-30b|unsloth/Nemotron-3-Nano-30B-A3B-GGUF:IQ4_XS|18.2|24|131072|0.6|0.95"
    "nemotron-30b-q8|unsloth/Nemotron-3-Nano-30B-A3B-GGUF:Q8_0|33.6|48|131072|0.6|0.95"
    "nemotron-super-49b|unsloth/Llama-3_3-Nemotron-Super-49B-v1_5-GGUF:Q4_K_M|30.2|48|32768|0.6|0.95"
)

field() { cut -d'|' -f"$2" <<< "$1"; }

# GPU environment
if [[ -z "${GPU:-}" ]]; then
    echo "Which GPU will you pick on Brev?"
    select g in "${GPUS[@]%%|*}"; do [[ -n "$g" ]] && GPU="$g" && break; done
    [[ -n "${GPU:-}" ]] || die "no GPU chosen"
fi
vram=""
for g in "${GPUS[@]}"; do [[ "${g%%|*}" == "$GPU" ]] && vram="$(field "$g" 2)"; done
[[ -n "$vram" ]] || die "unknown GPU '$GPU' (known: ${GPUS[*]%%|*})"

if [[ -z "${GPU_COUNT:-}" ]]; then
    read -rp "How many ${GPU}s? [1] " GPU_COUNT || true
    GPU_COUNT="${GPU_COUNT:-1}"
fi
[[ "$GPU_COUNT" =~ ^[1-9][0-9]*$ ]] || die "GPU_COUNT must be a positive number"
total=$(( vram * GPU_COUNT ))
echo "GPU environment: ${GPU_COUNT}x ${GPU} = ${total} GB VRAM"

# Model
fits=()
for p in "${PRESETS[@]}"; do (( $(field "$p" 4) <= total )) && fits+=("$(field "$p" 1)"); done

choice="${1:-}"
if [[ -z "$choice" ]]; then
    (( ${#fits[@]} )) || die "no preset fits ${total} GB; pass a smaller <hf-user>/<repo>:<quant>"
    echo "Pick a model (or rerun with any <hf-user>/<repo>[:<quant>]):"
    select choice in "${fits[@]}"; do [[ -n "$choice" ]] && break; done
    [[ -n "$choice" ]] || die "no model chosen"
fi

preset=""
for p in "${PRESETS[@]}"; do [[ "${p%%|*}" == "$choice" ]] && preset="$p"; done
if [[ -n "$preset" ]]; then
    IFS='|' read -r MODEL_ALIAS MODEL size need ctx temp top_p <<< "$preset"
    (( need <= total )) || echo "warning: $MODEL_ALIAS wants ~${need} GB VRAM, you have ${total} GB" >&2
else
    [[ "$choice" == */* ]] || die "unknown preset '$choice'"
    MODEL="$choice"
    MODEL_ALIAS="$(basename "${choice%%:*}" | sed 's/-GGUF$//I' | tr 'A-Z' 'a-z')"
    size="?" ctx=32768 temp=0.7 top_p=0.95
fi

# Build
declare -A VARS=(
    [MODEL]="$MODEL"
    [MODEL_ALIAS]="$MODEL_ALIAS"
    [LLAMA_API_KEY]="${LLAMA_API_KEY:-sk-$(openssl rand -hex 24)}"
    [CTX_SIZE]="${CTX_SIZE:-$ctx}"
    [PARALLEL]="${PARALLEL:-1}"
    [TEMPERATURE]="${TEMPERATURE:-$temp}"
    [TOP_P]="${TOP_P:-$top_p}"
    [N_CPU_MOE]="${N_CPU_MOE:-0}"
    [SPLIT_MODE]="${SPLIT_MODE:-layer}"
    [PORT]="${PORT:-8080}"
    [HF_TOKEN]="${HF_TOKEN:-}"
)

# Replace each ${VAR...} in the template with its value.
script=""
for k in "${!VARS[@]}"; do script+="s|\\\${$k[:?-][^}]*}|${VARS[$k]}|g;"; done
mkdir -p dist
{
    echo "# GENERATED by setup.sh on $(date -u +%Y-%m-%dT%H:%MZ) for ${GPU_COUNT}x ${GPU}, model ${MODEL}"
    echo "# DO NOT EDIT THIS FILE MANUALLY"
    sed "/^# Template/d; $script" docker-compose.yml
} > dist/docker-compose.yml

cat <<MSG

Built dist/docker-compose.yml  (${MODEL}, ~${size} GB download)

Upload on https://brev.nvidia.com/environment/new

Endpoint: http://<instance>:${VARS[PORT]}/v1   model: ${VARS[MODEL_ALIAS]}
API key:  ${VARS[LLAMA_API_KEY]}
MSG
